---
- name: Install Apache httpd on EC2
  hosts: all
  become: true
  remote_user: ec2-user
  vars:
    httpd_package: httpd

  tasks:
    - name: Install the latest version of Apache
      yum:
        name: "{{ httpd_package }}"
        state: latest

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Deploy HTML file
      copy:
        src: index.html
        dest: /var/www/html/index.html
